
server:       # 스프링부트 웹 애플리케이션인 구성서버는 기본적으로 8080을 리스닝한다. / 포트 충돌을 방지하기 위해 , 8888로 변경
  port: 8888  # 구성 서버 클라이언트가 구성 서버로부터 데이터를 가져올 때 사용하는 기본 포트가 8888
  
  
spring:       # 구성 서버가 클라이언트에 제공하는 구성 속성은, 이 원격 저장소에서 가져온다.
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inwoox/Spring_TacoDesign_Config
          #search-paths: config      # 하위 경로
          #default-label: sidework   # sidework 브랜치의 구성 속성을 가져온다.
          #username: aaa             # 백엔드 Git 리포지토리의 인증 정보 설정
          #password: bbb 
          

# 구성 서버가 가져올 속성을 준비하는 방법은 여러가지가 있지만,
# 가장 기본적이고 쉬운 방법으로, Git 리포지토리의 루트 경로로 application.yml 등을 PUSH하는 방법이 있다.

# 호출할 때는 curl localhost:8888/someapp/comeconfig 형태로 호출한다.
# 값을 사용하기 위해서는 Client 쪽에서 Properties를 이용해 값을 사용한다.