
# application.propertie 또는 application.yml을 통해 스프링부트의 자동 구성에 사용되는 스프링 부트의 구성 속성을 정의한다.
# 구성 속성은,  원천 속성 (JVM 시스템 속성, 환경 변수, 명령행 인자, 프로퍼티 파일, yml 파일)에 정의된 빈의 속성이다.
# 스프링 환경 추상화를 통해, 원천 속성을 추상화한다. 
# (원천 속성에서 구성 속성들을 추출해 한 군데로 모아서, 각 속성이 필요한 빈들에게 주입하고,  빈들은 원천 속성이 어디인지 알 필요가 없으므로 , 원천 속성은 추상화 된다.)


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: pass
   
  profiles:  # 좋은 방법이 아니다. 환경 변수나 명령행 인자를 통해 프로파일을 변경할 수 있어야한다.
    active:
      - dev

# 로깅 구성을 제어할 때는 classpath의 루트(src/main/resources)에 logback.xml 파일을 생성할 수 있지만 
# 스프링부트의 구성 속성을 사용하면 logback.xml 파일을 생성할 필요가 없다.
logging:
  file:
    path: /Users/a/Desktop/logs
    max-size: 500MB
    max-history: 10
  level:            # 설정한 레벨 이상의 로그만 출력 및 저장된다.
    root: INFO      # 레벨 설정에서 로깅 범위를, 패키지 단위로 설정할 수 있다.

taco:
  orders:
    pageSize: 10
    
#---

#spring:
#  profiles: prod
#  datasource: