

# 중앙 집중식 구성 서버가 있을 때는, 대부분의 모든 구성이 서버에서 제공되기 때문에, 마이크로서비스가 자신의 구성을 가질 필요가 없으며,
# 아래와 같이 구성 서버의 위치를 지정하는 uri와 구성 서버에 애플리케이션을 알려주는 name 속성만, 각 마이크로서비스에 설정하면 된다.

spring:
  application:
    name: client
  
  # 이 속성을 통해 클라이언트에게, 구성 서버의 위치를 알려준다 (설정하지 않으면, 기본적으로 자동 구성은 localhost:8888에서 서버가 실행 중인 것으로 간주)
  
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'